export const AGENT_CONFIG = Symbol('AGENT_CONFIG');
export const OPENAI_CLIENT_FACTORY = Symbol('OPENAI_CLIENT_FACTORY');
export const MODERATION_CLIENT_FACTORY = Symbol('MODERATION_CLIENT_FACTORY');
